<meta http-equiv="Content-Type" content="text/html;  charset=UTF-8">

<?php echo $this->getContent() ?>

<a style="width: 100%;background-color: #e93f36;padding: 13px;text-transform: uppercase;font: 500 12px/12px Arial;color: #fff;margin-top: 15px;border: none;border-radius: 4px;margin-left: 250px;box-shadow: 0 0 10px 0 rgba(0,0,0,.25);" href="/crvbank/processing/success">Ок</a>
<a style="width: 100%;background-color: #e93f36;padding: 13px;text-transform: uppercase;font: 500 12px/12px Arial;color: #fff;margin-top: 15px;border: none;border-radius: 4px;box-shadow: 0 0 10px 0 rgba(0,0,0,.25);" href="/crvbank/index/index/folder/bank/file/<?php echo $this->getOrder() ?>.pdf">Скачать</a>
